name: Workflow 1
on: push

jobs: 
    job1: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
          
            - name: Action message
              run: echo "Ping Message"

            - name: List files
              run: ls
